version: 2
mergeable:
  - when: pull_request.*, issues.*
    name: 'Auto assign to author if no assignee is set'
    validate:
      - do: assignee
        min:
          count: 1
    fail:
      - do: assign
        assignees: [ '@author' ]
